#!/bin/sh
set -eu

git fetch

git submodule foreach --quiet '\
  cd "$toplevel" \
  && git diff origin/release...origin/master --submodule=log -- "$path" \
     | sed -e "s/Submodule //" \
     | grep -s "." \
     && echo "" \
  ; cd "$OLDPWD"\
'
