#!/bin/sh
set -eu

git fetch --quiet

echo "Changes between origin/release and origin/next"
echo ""

git submodule foreach --quiet '\
  cd "$toplevel" \
  && git diff origin/release...origin/next --submodule=log -- "$path" \
     | sed -e "s/Submodule //" \
     | grep -s "." \
     && echo "" \
  ; cd "$OLDPWD"\
'
