releases:

### NEXT ######################################################################

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: 'rc.0'
  name: Tinguely
  info_url: https://de.wikipedia.org/wiki/Jean_Tinguely
  description: |
    First release candidate of the next version of Madek.

### CURRENT  ##################################################################
