releases:

### CURRENT #######################################################################

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: '6.0'
  name: Béjart
  info_url: 'https://de.wikipedia.org/wiki/Maurice_Béjart'
  description: |

    ## Changes:

    ### webapp

    - feat: add MetaData Contexts tabs for Sets
    - feat: ui: AutoComplete: "prefill" fixed keywords
    - feat: ui: AutoComplete: style existing values, show pending and empty results
    - feat: backend: add support to sign-in with shibboleth
    - fix: controller: fix resource permissions helper
    - fix: translations: "imports" -> "drafts"

    ### api

    - fix: preview permission is sufficient for getting the media-file resource

    ### admin-webapp
    - feat: Settings: manage Teaser Set & Extra Contexts for Collection View
    - feat: make 'is_extensible_list' available only for MetaDatum::Keywords
    - feat: add Allowed Subtypes for MetaDatum::People form

    ### deploy
    - initial support for shibboleth auth

### HISTORY  ######################################################################

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: '5.0'
  name: Oppenheim
  info_url: 'http://www.sikart.ch/KuenstlerInnen.aspx?id=4000327&lng=de'
  description: |

    First pre-release for "Oppenheim".

    Changes:
    ========

    webapp
    ------
      - feat: CollectionRelations: show all
      - feat: CollectionShow: children type switcher
      - feat: display progress of processed files with Zencoder
      - feat: views: Vocabulary info pages
      - feat: sort set by last change
      - fix: MetaDataEdit: don't submit form on enter
      - fix: Explore: larger teaser images
      - fix: PermissionsEdit: fullwidth inputs
      - fix: close set dialog before forward

    admin-webapp
    ------------
      - feat: display progress of processed files with Zencoder

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: '4.0'
  name: Tinguely
  info_url: https://de.wikipedia.org/wiki/Jean_Tinguely
  description: |

    Fourth pre-release for Tinguely.

    Changes:
    ========

    General and DB:
    ---------------
    - Rework migration: consolidate ZHdK institutional groups
    - Adjust constraints on users table
    - Add login/email constraints on users table; adjust specs
    - Clean up meta and context keys; add related DB constraints
    - migrate meta data groups
    - extract ZencoderRequester as common part

    webapp
    ------
    - feat: view: app: only show 'my' nav if logged in
    - feat: show edit sessions
    - feat: sorting for set children
    - feat: ui: forms: Input TextDate

    - fix: ui: MetaDatumGroups - MetaDatumPeople
    - fix: translations (minor text fixes)
    - fix: controller: don't check CSRF when accepting usage terms
    - fix: view: Home: welcome message from AppSettings

    admin-webapp
    ------------
    - feat: reencode video with Zencoder
    - fix: after switching to another user redirect to his archive

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: '3.0'
  name: Tinguely
  info_url: https://de.wikipedia.org/wiki/Jean_Tinguely
  description: |

    Third pre-release for Tinguely.

    Changes:
    ========

    General and DB:
    ---------------
      - Apply Unicode Normalisation to MetaDatumTexts and Keywords.

    webapp a7dc84e..2c13515:
    -------------------------
      - feat: "list" view (with MetaData) for Sets
      - feat: "tile" view for all Listings (Entries and Sets)
      - feat: show PDFs in browser (if supported)
      - feat: save layout for sets, show saved layout by default
      - feat: log into edit_sessions
      - fix: don't try to show "Set Highlights" that are hidden for user
      - fix: explore: count for 2nd level & specs
      - fix: routes: add legacy redirects
      - fix: better ranking of autocomplete search results
      - visual fixes

    admin-webapp:
    ------------­
      - list also not published Media Entries, add corresponding filter

    api:
    ---
      - fix: missing docs for collections & filter_sets
      - fix: meta_key id regex & update docs

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: 'rc.1'
  name: Tinguely
  info_url: https://de.wikipedia.org/wiki/Jean_Tinguely
  description: |
    Second release candidate of the next version of Madek.

    Changes:
      * fix: API doc links in the API browser
      * fix: API meta_key id regex check and docs
      * fix: proper counts on explore catalog 2nd level page
      * fix: rewrite HTTP-redirect to HTTPs when using HTTPs
      * fix: MediaPlayer post image
      * fix: validation of new meta data for required context keys
      * feat: use configured site_title as html title
      * feat: set a default license/usage on upload
      * feat: use configured site_title as html title

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: 'rc.0'
  name: Tinguely
  info_url: https://de.wikipedia.org/wiki/Jean_Tinguely
  description: |
    First release candidate of the next version of Madek.
