releases:

### CURRENT #######################################################################

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: '10.1'
  name: Miedinger
  info_url: 'https://en.wikipedia.org/wiki/Max_Miedinger'
  description: |

    Admin enhancements, a simple HD toggle for the video player and small fixes.

    ## Changes

    ### webapp
    - feat: player: HD toggle
    - fix: app: more secure authentication
    - fix: deprecate License, make them behave like keywords
    - fix: presenters: display of user permissions

    ### admin
    - feat: improve meta key creation/update
    - feat: MetaKeys can be renamed and even moved
    - feat: style: forms for "new" actions have a yellowish background
    - fix: MetaKeys: enhance edit and move forms
    - fix: MetaKeysCreation: auto-correct given id (vocabulary prefix)

    ### deploy
    - reverse-proxy: enable HSTS when using certbot
    - reverse-proxy: avoid duplicate header
    - reverse-proxy: add Forwarded-Proto header


### HISTORY  ######################################################################

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: '10.0'
  name: Miedinger
  info_url: 'https://en.wikipedia.org/wiki/Max_Miedinger'
  description: |

    ## Changes

    ### admin-webapp
      - vocabularies: improve ui
      - fix meta key with People type creation

    ### webapp
      - feat: view: VocabulariesIndex: list MetaKeys
      - feat: view: Vocabulary: Permissions tab
      - feat: view: VocabularyPermissions: group edit button
      - feature: add relation counts to usage data
      - feature: split more_data into more_data and usage_data
      - fix: do not show keyword checkboxes if extensible
      - fix: for transfer responsibility remove existing permissions for new user
      - fix: meta data edit: extareas
      - fix: meta data listing layout and texts
      - fix: never set newly created Sets 'public'
      - fix: only show delete icon on flyout if destroyable instead of editable
      - fix: only show vocab keywords if content available
      - fix: permissions layout and labels
      - fix: show detailed name for institutional groups on permissions form
      - fix: style: allow multine-line tag cloud items
      - fix: style: MediaPlayer: fullscreen background
      - fix: ui: cleanup url params in box links
      - fix: ui: more careful auto-linking for MetaDatumText
      - fix: ui: Vocabulary pages borders
      - perf: memoize `current_user`

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: '9.0'
  name: Celtic Frost
  info_url: 'https://de.wikipedia.org/wiki/Celtic_Frost'
  description: |

    Adds functionality to transfer responsibility of Entries and Sets to another user,
    plus many fixes and performace enhancements (especially image-related)

    ## changes

    ### webapp
      - feat: transfer responsibility
      - fix: view: increase resource box auto-loading
      - fix: view: shuffle teaser and catalog images
      - fix: view: image preview handling
      - fix: view: collection highlights preview display
      - fix: my: ActivityStream: remove 'beta', fallback message
      - fix: keyword/term routes

    ### admin-webapp
      - fix: webapp_keyword_path
      - fix keywords & meta keys ordering
      - fix: compute keyword usage correctly

    ### deploy
      - reverse-proxy: enable letsencrypt cert if present

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: '8.0'
  name: Glauser
  info_url: 'https://de.wikipedia.org/wiki/Friedrich_Glauser'
  description: |

    **webapp**

      - several fixes, some security related
      - add custom urls management
      - improved MetaData editing
      - better Vocabulary-related UI

    **admin-webapp**

      - provide UI to cleanup keywords
      - create/duplicate Context from Context/Vocab

    **general**

      - core vocabulary fixes and improvements
      - improved deploy, especially for first-time setup

    ## changes

    ### admin-webapp
    - feat: provide keywords management
    - feat: create/duplicate Context from Context/Vocab
    - fix: hide "re-encode missing" features

    ### deploy
    - deploy-info: "deploy time", "is_latest_release"
    - build: add changes since last release
    - fix: apache: add ServerName
    - fix: build: deploy_info: time -> build_time
    - fix: monit: restart instead of reload
    - test: container: run first-time-setup playbook
    - add playbook 'first-time-setup'

    ### webapp
    - fix(security): policy: enforce correct permissions for update permissions
    - fix(security): export: don't serve HTML uploads as HTML
    - feat: add confirmation dialog to custom urls transfer and adjust flash messages
    - feat: custom urls management
    - feat: embed edit meda data by vocabulary inside a tab
    - feat: explore menu entry to vocabularies
    - feat: vocabulary quick links in meta data edit by vocabulary
    - feat: view: release: more deploy info
    - fix: ActivityStream: section name, more formal language
    - fix: disable save button logic
    - fix: meta data edit tests
    - fix: only show extra contexts which have meta data content
    - fix: only show links for vocabulary titles, not for context titles
    - fix: remove filter set saving from dropdown
    - fix: routes: keyword terms, fixes
    - fix: style: MediaPlayer: remove ghostlines
    - fix: vocabulary title links should look the same everywhere

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: '7.5'
  name: Petitpierre
  info_url: 'http://www.sikart.ch/KuenstlerInnen.aspx?id=4026301'
  description: |

    webapp: better Vocabulary Pages and lots of small fixes

    ## changes

    ### webapp
      - feat: add vocabulary links to „more data“ view
      - feat: add hint texts to relations page
      - feat: release info: deploy and dev info, all releases
      - feat: vocabulary contents
      - feat: release info page
      - feat: meta data edit thumbnail links to media preview
      - fix: autocomplete dropdown width
      - fix: InputTextDate: fix missing inputs
      - fix: style: consistent font rendering (webkit)
      - fix: routes: fix terms with special characters
      - fix: use larger previews for thumbnail link on meta data edit
      - fix: hint texts for vocabulary keywords and contents
      - fix: relations texts and layouting
      - fix: vocab link color; fix: relations texts and layout

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: '7.4'
  name: Petitpierre
  info_url: 'http://www.sikart.ch/KuenstlerInnen.aspx?id=4026301'
  description: |

    Admin: New audio/video batch re-encoding process.
    Webapp: Better file downloads and PDF viewing fixes;
    customizable HTML (e.g. custom styles or analytics).

    ## Changes

    ### webapp
      - feat: view: layout: add extra content from settings
      - fix: overwrite content type application/x-pdf with application/pdf
      - fix: use filename with extension for original and preview file downloads

    ### admin
      - media_files: client/server batch encoding process
      - fix: app-settings: hide secrets from deploy-config (Madek/madek_admin-webapp#1)

    ### deploy
      - @zhdk: add HD video previews
      - @zhdk: add piwik tracking code
      - add settings for webapp extra html content

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: '7.3'
  name: Petitpierre
  info_url: 'http://www.sikart.ch/KuenstlerInnen.aspx?id=4026301'
  description: |

    adds media files view mass re-encoding of audio files to the admin ui.

    ## Changes

    ### admin-webapp
      - feat: view: add deploy config to app_settings#index
      - feat: media files listing with filters, mass re-encoding of audio files

    ### deploy
      - zencoder: set audio codec to mp3
      - @zhdk: update AGW and zencoder config

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: '7.2'
  name: Petitpierre
  info_url: 'http://www.sikart.ch/KuenstlerInnen.aspx?id=4026301'
  description: |

    fixes and performance enhancements

    ## Changes:

    ### webapp
      - feature: add relations pages for media entries (consistent with collections)
      - feat: *beta* add ActivityStream / dashboard timeline
      - fix: set return to for cancel button on meta data batch edit fallback form
      - fix: null title for drafts in fallback meta data edit form
      - fix: ui: VideoPlayer fullscreen styles
      - fix: hacky workaround for buggy ActiveRecord. Sad.

    ### deploy
      - templates/rails.service: start puma in production env
      - inventory: disable shibboleth on test-blank
      - feat: archive-build: add datalayer tree id

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: '7.1'
  name: Petitpierre
  info_url: 'http://www.sikart.ch/KuenstlerInnen.aspx?id=4026301'
  description: |

    hotfix release, fixes Audio Entries

    ## Changes:

    ### webapp

    - hotfix: audio player/audio entry view

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: '7.0'
  name: Petitpierre
  info_url: 'http://www.sikart.ch/KuenstlerInnen.aspx?id=4026301'
  description: |

    ## Changes:

    ### webapp

    - feat: batch edit Collection Permissions
    - feat: collection batch meta data edit
    - feat: meta data edit grouping
    - feat: oEmbed API, embedded API, video player
    - feat: sort meta_key keywords if required for meta_key
    - feat: use meta_data_updated_at for sorting by last change
    - feat: view: my: add Vocabularies link to sidebar
    - feat: vocabulary keywords overview
    - fix: fix MetaDatumText inputs (line vs block/textarea)
    - fix: add-to-/remove-from-set dropdown actions
    - fix: do not show actions dropdown on upload page
    - fix: enable links for vocabulary keywords
    - fix: highlights shows duplicates because of concat
    - fix: better hightlight selected collections
    - fix: session: default to persisted cookies, set to 2 weeks (ipad video bug)
    - fix: show all children for edit cover and edit highlights
    - fix: show selection dropdown again for collections
    - fix: ui: add more labels
    - fix: ui: VideoPlayer default sizing
    - fix: view: dashboard: only show Vocabularies link in sidebar
    - perf: boost presenter api / dump speed

    ### api

    - feat: add collection-media-entry-arcs
    - feat: attributes :edit_session_updated_at, :meta_data_updated_at on collection and media_entry
    - feat: Increase the default per page from 10 to 100
    - feat: sort keywords for meta_key if required for meta_key
    - feat: use meta_data_updated_at for sorting by last change
    - fix: permission bug: get_metadata_and_previews was sufficient to download original

    ### admin-webapp

    - fix: adjust edit forms for new MetaKey. text_type

    ### deploy

    - config: zhdk: add setting ui_bundle_context_keys

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: '6.0'
  name: Béjart
  info_url: 'https://de.wikipedia.org/wiki/Maurice_Béjart'
  description: |

    ## Changes:

    ### webapp

    - feat: add MetaData Contexts tabs for Sets
    - feat: ui: AutoComplete: "prefill" fixed keywords
    - feat: ui: AutoComplete: style existing values, show pending and empty results
    - feat: backend: add support to sign-in with shibboleth
    - fix: controller: fix resource permissions helper
    - fix: translations: "imports" -> "drafts"

    ### api

    - fix: preview permission is sufficient for getting the media-file resource

    ### admin-webapp
    - feat: Settings: manage Teaser Set & Extra Contexts for Collection View
    - feat: make 'is_extensible_list' available only for MetaDatum::Keywords
    - feat: add Allowed Subtypes for MetaDatum::People form

    ### deploy
    - initial support for shibboleth auth

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: '5.0'
  name: Oppenheim
  info_url: 'http://www.sikart.ch/KuenstlerInnen.aspx?id=4000327&lng=de'
  description: |

    First pre-release for "Oppenheim".

    Changes:
    ========

    webapp
    ------
      - feat: CollectionRelations: show all
      - feat: CollectionShow: children type switcher
      - feat: display progress of processed files with Zencoder
      - feat: views: Vocabulary info pages
      - feat: sort set by last change
      - fix: MetaDataEdit: don't submit form on enter
      - fix: Explore: larger teaser images
      - fix: PermissionsEdit: fullwidth inputs
      - fix: close set dialog before forward

    admin-webapp
    ------------
      - feat: display progress of processed files with Zencoder

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: '4.0'
  name: Tinguely
  info_url: https://de.wikipedia.org/wiki/Jean_Tinguely
  description: |

    Fourth pre-release for Tinguely.

    Changes:
    ========

    General and DB:
    ---------------
    - Rework migration: consolidate ZHdK institutional groups
    - Adjust constraints on users table
    - Add login/email constraints on users table; adjust specs
    - Clean up meta and context keys; add related DB constraints
    - migrate meta data groups
    - extract ZencoderRequester as common part

    webapp
    ------
    - feat: view: app: only show 'my' nav if logged in
    - feat: show edit sessions
    - feat: sorting for set children
    - feat: ui: forms: Input TextDate

    - fix: ui: MetaDatumGroups - MetaDatumPeople
    - fix: translations (minor text fixes)
    - fix: controller: don't check CSRF when accepting usage terms
    - fix: view: Home: welcome message from AppSettings

    admin-webapp
    ------------
    - feat: reencode video with Zencoder
    - fix: after switching to another user redirect to his archive

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: '3.0'
  name: Tinguely
  info_url: https://de.wikipedia.org/wiki/Jean_Tinguely
  description: |

    Third pre-release for Tinguely.

    Changes:
    ========

    General and DB:
    ---------------
      - Apply Unicode Normalisation to MetaDatumTexts and Keywords.

    webapp a7dc84e..2c13515:
    -------------------------
      - feat: "list" view (with MetaData) for Sets
      - feat: "tile" view for all Listings (Entries and Sets)
      - feat: show PDFs in browser (if supported)
      - feat: save layout for sets, show saved layout by default
      - feat: log into edit_sessions
      - fix: don't try to show "Set Highlights" that are hidden for user
      - fix: explore: count for 2nd level & specs
      - fix: routes: add legacy redirects
      - fix: better ranking of autocomplete search results
      - visual fixes

    admin-webapp:
    ------------­
      - list also not published Media Entries, add corresponding filter

    api:
    ---
      - fix: missing docs for collections & filter_sets
      - fix: meta_key id regex & update docs

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: 'rc.1'
  name: Tinguely
  info_url: https://de.wikipedia.org/wiki/Jean_Tinguely
  description: |
    Second release candidate of the next version of Madek.

    ##Changes

      * fix: API doc links in the API browser
      * fix: API meta_key id regex check and docs
      * fix: proper counts on explore catalog 2nd level page
      * fix: rewrite HTTP-redirect to HTTPs when using HTTPs
      * fix: MediaPlayer post image
      * fix: validation of new meta data for required context keys
      * feat: use configured site_title as html title
      * feat: set a default license/usage on upload
      * feat: use configured site_title as html title

- version_major: 3
  version_minor: 0
  version_patch: 0
  version_pre: 'rc.0'
  name: Tinguely
  info_url: https://de.wikipedia.org/wiki/Jean_Tinguely
  description: |
    First release candidate of the next version of Madek.
